# Generated by Django 2.2.3 on 2019-07-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('cin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=62, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('cne', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=62, unique=True)),
                ('sujet', models.TextField()),
                ('etablissement', models.CharField(max_length=100)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('justifiee', models.BooleanField()),
                ('cne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_.Stagiaire')),
            ],
        ),
    ]
