# Generated by Django 2.2.3 on 2019-07-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0002_auto_20190722_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='A_Image',
            field=models.ImageField(default='admin/téléchargement(1).png', upload_to='admin'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='S_Image',
            field=models.ImageField(default='stagiaire/téléchargement.png', upload_to='=stagiaire'),
        ),
    ]
