# Generated by Django 2.2.3 on 2019-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0004_auto_20190722_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='A_Image',
            field=models.ImageField(blank=True, default='admin/téléchargement(1).png', null=True, upload_to='admin'),
        ),
    ]
