# Generated by Django 2.2.3 on 2019-07-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0006_auto_20190722_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
