# Generated by Django 2.2.3 on 2019-08-02 11:35

import admin_.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0007_auto_20190722_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='cv',
            field=models.FileField(default='stagiaire/Youssef_CV.pdf', upload_to=admin_.models.user_directory_path_cv),
        ),
        migrations.AlterField(
            model_name='admin',
            name='A_Image',
            field=models.ImageField(blank=True, default='admin/admin.jpg', null=True, upload_to='admin'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='S_Image',
            field=models.ImageField(blank=True, default='stagiaire/l60Hf.png', null=True, upload_to=admin_.models.user_directory_path),
        ),
    ]
