# Generated by Django 2.2.3 on 2019-08-04 12:48

import admin_.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0008_auto_20190802_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='cv',
            field=models.FileField(upload_to=admin_.models.user_directory_path_cv),
        ),
    ]
