# Generated by Django 2.2.4 on 2019-08-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0009_auto_20190804_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phoneNumber',
            field=models.CharField(default='+2126482315474', max_length=20),
        ),
    ]
