# Generated by Django 2.2.4 on 2019-08-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0010_admin_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='S_Image',
            field=models.ImageField(blank=True, default='stagiaire/l60Hf.png', null=True, upload_to='admin/image'),
        ),
    ]
