# Generated by Django 2.2.4 on 2019-08-14 12:57

import admin_.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0011_auto_20190814_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='S_Image',
            field=models.ImageField(blank=True, default='stagiaire/l60Hf.png', null=True, upload_to=admin_.models.user_directory_path),
        ),
    ]
