# Generated by Django 2.2.4 on 2019-08-14 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('admin_', '0012_auto_20190814_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='phoneNumber',
            new_name='Numero_De_Telephone',
        ),
    ]
